
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: dockerfile.api
    environment:
      DEBUG: 'true'
      SECRET_KEY: 'fPPkMB4B2OduIcpiA0Gh9B2IOomEDP1ZWAes'
      DB_URL: 'mongodb://mongo:root@mongo'
    entrypoint: 'gunicorn run:app -c gunicorn.py'
    networks:
      - api_network

  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=autonomia
    image: mongo
    volumes:
      - api_db_data:/data/db
    networks:
      - api_network

  mongo_client:
    container_name: mongo_client
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_SITE_BASEURL=/mongodb/
      - ME_CONFIG_BASICAUTH_PASSWORD=Admin@2024!
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - api_db_data:/data/db
    networks:
      - api_network

volumes:
  api_db_data:

networks:
  api_network:
    external: true