
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: dockerfile.api
    environment:
      DEBUG: 'false'
      SECRET_KEY: 'fPPkMB4B2OduIcpiA0Gh9B2IOomEDP1ZWAes'
      DB_URL: 'mongodb://mongo:root@mongo_db'
    entrypoint: 'gunicorn run:app -c gunicorn.py'
    networks:
      - api_network

  mongo_db:
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo
    volumes:
      - api_db_data:/data/db
    networks:
      - api_network

volumes:
  api_db_data:

networks:
  api_network:
    external: true