version: "3"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: dockerfile.api
    volumes:
      - api_data:/api/
    ports:
      - '5000:5000'
    environment:
      DEBUG: false
      SECRET_KEY: fPPkMB4B2OduIcpiA0Gh9B2IOomEDP1ZWAes
    entrypoint: gunicorn --bind 0.0.0.0:5000 --timeout 120 --access-logfile api_log --worker-class gevent run:app

  mongo:
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo

volumes:
  api_data: